[package]
name = "rcli"
version = "0.1.0"
authors = ["Matt <matt@matt.com>"]
edition = "2024"

[dependencies]
clap = { version = "4.5.47", features = ["derive"] }
csv = "1.3.1"
serde = { version = "1.0.225", features = ["derive"] }
